// Generated by CoffeeScript 1.9.1
(function() {
  var correction, traduction;

  traduction = function(dutexte) {
    var texte;
    texte = dutexte;
    texte = texte.replace(/\ dans\ /g, " in ");
    texte = texte.replace(/pour\ /g, "for ");
    texte = texte.replace(/Pour\ /g, "for ");
    texte = texte.replace(/Sinon/g, "else");
    texte = texte.replace(/sinon/g, "else");
    texte = texte.replace(/Si\ /g, "if ");
    texte = texte.replace(/\ nouvelle\ /g, " new ");
    texte = texte.replace(/Tant que\ /g, "while ");
    texte = texte.replace(/Jusqu'à ce que\ /g, "until ");
    texte = texte.replace(/\ devient\ /g, " = ");
    return texte;
  };

  correction = function(unAlgo) {
    var texte;
    texte = unAlgo;
    texte = texte.replace(/.foisFaire/g, " fois faire");
    return texte;
  };


  /*présentation
   */

  $(function() {
    $("#manuel, #academy").hide(10);
    $("#syntaxe").on("click", function() {
      return $("#manuel").toggle(1000);
    });
    $("#porteparole").on("click", function() {
      return $("#academy").toggle(1000);
    });
    $("#transfert").on("click", function() {
      $("#academy").show(1000);
      return $("#academy").val(correction($("#scriptCoff0").val()));
    });
    return $("#runCoff0").on("click", function() {
      var e;
      try {
        return eval(CoffeeScript.compile(traduction($("#scriptCoff0").val())));
      } catch (_error) {
        e = _error;
        return alert(e);
      }
    });
  });

}).call(this);
