// Generated by CoffeeScript 1.9.1

/*présentation
 */

(function() {
  $(function() {
    $("#manuel, #academy").hide(10);
    $("#syntaxe").on("click", function() {
      return $("#manuel").toggle(1000);
    });
    $("#porteparole").on("click", function() {
      return $("#academy").toggle(1000);
    });
    return $("#runCoff0").on("click", function() {
      var e;
      try {
        return eval(CoffeeScript.compile($("#scriptCoff0").val()));
      } catch (_error) {
        e = _error;
        return alert(e);
      }
    });
  });

}).call(this);
